"use client";

interface FinalReviewTextProps {
  reviewText: string;
  onApprove: () => void;
  onRequestRevision: () => void;
}

export default function FinalReviewText({
  reviewText,
  onApprove,
  onRequestRevision,
}: FinalReviewTextProps) {
  return (
    <div className="w-full lg:w-[410px] bg-white border border-[#001BD2]/20 shadow-[0px_1px_2px_rgba(0,0,0,0.05)] rounded-2xl p-6 flex flex-col gap-4 font-manrope text-left justify-between flex-grow">
      
      {/* Header */}
      <div className="flex justify-between items-center w-full border-b border-slate-50 pb-3">
        <div className="flex items-center gap-2">
          <span className="text-[#001BD2] text-xs">📝</span>
          <span className="text-xs font-bold text-[#454656]/60 tracking-[1.2px] uppercase">
            FINAL REVIEW TEXT
          </span>
        </div>
        <span className="bg-[#EFF6FF] text-[#001BD2] text-[10px] font-bold px-2 py-0.5 rounded">
          GENERATED BY AI
        </span>
      </div>

      {/* Paragraph Body */}
      <div className="text-sm text-[#131B2E] leading-[23px] py-1 font-medium">
        &quot;{reviewText || "I'm usually skeptical of decaf options, but Nibbl's Zen Mode No-Caf really delivered. It has a rich, bold flavor profile that mirrors high-quality arabica beans without any of the jitteriness. It's become my go-to evening routine for winding down while still enjoying the ritual of coffee."}&quot;
      </div>

      {/* Footer Separator & Controls */}
      <div className="border-t border-[#C5C5D9]/10 pt-4 flex flex-row justify-end items-center gap-4 mt-2">
        <button
          onClick={onRequestRevision}
          className="text-xs font-bold text-[#454656] hover:underline cursor-pointer bg-transparent border-none"
        >
          Request Revision
        </button>
        
        <button
          onClick={onApprove}
          className="px-6 h-9 bg-[#001BD2] hover:bg-blue-700 text-white text-xs font-bold rounded-full transition-colors cursor-pointer border-none flex items-center justify-center shadow-sm"
        >
          Approve & Publish
        </button>
      </div>

    </div>
  );
}
